# attemp1
version: "3"
services:

  t2server:
    image: registry.cn-hangzhou.aliyuncs.com/onlinejudge/judge_server
    container_name: t2s
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://judge-server:8080
      - BACKEND_URL=http://oj-backend:8000/api/judge_server_heartbeat/
      - TOKEN=CHANGE_THIS
      # - judger_debug=1
    ports:
      - "8080:8080"
  
  t2backend:
    build: ./oj
    container_name: t2b
    restart: always
    depends_on:
      - t2server
    volumes:
      - ./oj:/app
      - ./data/backend:/data
    environment:
      - JUDGE_SERVER_TOKEN=CHANGE_THIS
    ports:
      - "8100:8100"

